### ISSUE TITLE
The annotate() method for NLP apps

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-python#20]
The `annotate()` method is most likely the same for each NLP app, as long as they all define `_add_tool_output()`. We could create a subclass `ClamsNLPApp` which has the `annotate()` method. 

Putting this in here for future reference, doing anything on this now is somewhat premature.

**Comment by keighrim** [comment]
So, the `ClamsNLPApp` `ABC` would implement `ClamsApp::annotate` while adding another abstract method `ClamsNLPApp::_add_tool_output`. 

As an `ABC`, I see `ClamsApp` as a consistent requirement specification for all the apps runs on CLAMS platform, and with that I'd like to keep the abstract API as simple as possible. 

Also I guess this assumes all NLP applications *will* process all the `TextDocument` instances found in the input MMIF, which may not necessarily be true depending on how a developer implements their app. For instance, there could be an NLP app that only want to deal with "gold standard" data and ignore all machine-generated `TextDocument` instances. Or one can develop a NLP tool that spell-corrects OCR results (@eholderness95 maybe?) , and that would be using not all `TextDocument`.

**Comment by marcverhagen** [comment]
I see the value of keeping CLAMS App simple, it was a nice surprise when I first looked at the code. It looks like you have no objection to creating sub classes for convenience, even if they live in the same package as ClamsApp. 

> I guess this assumes all NLP applications will process all the TextDocument instances found

That is definitely what the spacy app does. But I do not necessarily assume all text documents will always be processed. That whole issue on sniffing in #21 was partially to deal with the scenario you bring up.

**Comment by keighrim** [comment]
Since [`get_documents_by_type` was introduced](https://github.com/clamsproject/mmif-python/commit/89f5966c869e6653d41ffc61f0bc6aee62ec9f9f) in `mmif-python`, looping through all `TextDocuments` has been a single line of code. So it seems that what `_add_tool_output` can provide now is saving one indentation level.

**Comment by keighrim** [comment]
I believe many helper functions added to the `mmif-python` since this issue was open eliminates the necessity of this. Also, if we need special handling of `TextDocument`s, we can add more helpers to `mmif-python.utils` pakcage as we did for `VideoDocument`s (https://github.com/clamsproject/mmif-python/issues/229). Closing this as won't-fix.
