### ISSUE TITLE
The art of sniffing

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-python#21]
The `sniff()` method now returns true or false, but this is problematic when you have more input candidates than just one document, which is often the case for NLP apps and which may be the case for other apps in the future. The thing is that some documents (with their associated views) may match the requirements and others don't, which makes sniffing essentially useless because it gives a single answer.

We could instead re-envision a sniffer as something that goes through (sniffs) all the documents and returns those that provide input for the app, with for each document the views that have the needed data. Here are some examples.

For the Slate detection application sniffing returns the single video document in the documents list:

```python
>>> slate_app.sniff(mmif)
[('d1', [])]
```

The Tesseract application, both vanilla and segmented. The return value says that document 'd4' is a video document and, for the segmented version, that view  'v6' has the bounding boxes (at certain time points and coordinates in the video). 

```python
>>> tesseract_app.sniff(mmif)
[('d4', [])]
>>> segmented_tesseract_app.sniff(mmif)
[('d4', ['v6'])]
```

For spaCy sniffing returns a list of text documents, some from within views.

```python
>>> spacy_app.sniff(mmif)
[('d1', []), ('v8:d1', []), ('v8:d2', []), ('v9:d1', [])]
```

A hypothetical NER Linking application that runs on the output of spaCy adds the views that spaCy created. 

```python
>>> ner_linking_app(mmif)
[('d1', ['v9']), ('v8:d1', ['v10']), ('v8:d2', ['v10']), ('v9:d1', ['v11'])]
```

The second element of each pair is a list because the information needed could be spread out over more than one view.  The method could also return actual documents and views instead of identifiers.

While sniffing views we can use the contains dictionary on the view metadata.

As a side note, if we have a document with an associated view that matches requirements (for example for SegmentedTesseract there is a video document that has an associated view with BoundingBox annotations with type=text), then we should use that document and view as input to Tesseract even if the annotations list is empty. So Tesseract would just loop through an empty list and not create output, and definitely not crash although it may report warnings.

This might be a somewhat involved change. For now, we can just assume that for non-NLP apps `sniff()`  just returns true or maybe does some minor testing. I may experiment with a simple tokenizer application that I wrote to see how this pans out for NLP applications. It would change the `annotate` method as it is now.

**Comment by keighrim** [comment]
Yeah, my old dream of quick and dirty sniffing was mostly based on the top-level `contains` map, which no longer exists. Anyway, the `sniff` method is bound to a http verb that returns simple http responses (only codes, no body) based on the boolean values the `sniff` returns. My initial thought was that we can use that HTTP calls in validating pipelines, but never had a concrete idea of how to do it. With this approach, sniffing is now a preprocessor for `annotate` rather than a validation tool, so it won't make much sense to have it as one of HTTP APIs. And lastly, I want to point out that there are apps that takes multiple documents together as its input; e.g. forced aligner will take a `TextDocument` and `AudioDocument` or `VideoDocument`. With tuples as described above might not be a proper structure to handle such apps.

**Comment by marcverhagen** [comment]
So we keep `sniff` as an abstract method, but remove its link to the POST request, right?

> there are apps that takes multiple documents together as its input

There goes my dream of keeping that simple. On that issue, we are now always working with only one document of each type in the documents list. If we allow more than one then we have no way of knowing how to run the alignment without knowledge of the internals of the MMIF file (that is, where to find the two documents to be aligned). This may be problematic when building pipelines. One option there is that the sniff method returns an audio/video and text document only if it finds one of each and then just assumes they need to be aligned. In this context I was also thinking of at some point maybe having tools that take one audio/video document and one text document and create a MMIF file that has a view with an Alignment annotation type that links the two documents and then the sniff method could be looking for that.

For now, we are good with our current blessed reality that MMIF files never have more than two documents of the same type in the documents list.

Finally, while MMIF does not have a contains dictionary at the top level anymore, there is nothing to stop the Mmif class from building such a dictionary, but I don't think that will all of a sudden a simple sniff with simple responses possible.

**Comment by keighrim** [comment]
With unbinding of `POST` and `sniff()`, this could be a good chance to confirm mapping of other verbs are proper.

**Comment by keighrim** [comment]
At today's meeting, we decided to unbind `POST` from `sniff` and bind it with `annotate`. `sniff` could be a part of `annotate` (as a validation step) but we didn't decide all the details regarding the future of `sniff` yet.

**Comment by keighrim** [comment]
Most of the features suggested in the initial comment are now implemented in `mmif-python` (examples; [get_all_views_contain](https://clams.ai/mmif-python/latest/autodoc/mmif.serialize.html#mmif.serialize.mmif.Mmif.get_all_views_contain), [get_views_contain](https://clams.ai/mmif-python/latest/autodoc/mmif.serialize.html#mmif.serialize.mmif.Mmif.get_views_contain)), and app specific implementation should really be part of `_annotate` method, given all the complexity we have added since. 

Closing the issue as *won't fix*.
