### ISSUE TITLE
metadata property names

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-python#80]
We have `wrappee_version`,  `wrappee_license`, `app_version`, and `license`. It might be more consistent to use `app_license` instead of `license`.

And can we find a better word for `wrappee`?

**Comment by keighrim** [comment]
Yeah, I agree on adding `app_` prefix. I also don't like the word choice of wrappee. Here's some random words I can think of now (in a random order)

* kernel_
* origin_
* core_
* upstream_
* bound_

**Comment by marcverhagen** [comment]
Actually, `wrappee` is not a word and if it were it would have meant "the thing that wraps" while it is used as "the thing that is wrapped". We did have some discussion on what `app` means a while ago and while I do not remember the outcome we now consider the entire application with third-party software and the CLAMS wrapper as the app.

In LAPPS we had `wrapper` as a way to refer to the code we created around Stanford et al, cannot use that here. 

I cannot get enthusiastic about any of the five random words. The best I have is `tool_` indicating that the app wraps some processing tool.

**Comment by keighrim** [comment]
We remember we had a conversation over the decision that landed on the term `app`, instead of `tool` or `service`. I'd rather avoid re-introducing the term `tool` (even in a difference context), as we might have old usages of `tool` from the past when we interchangeably used tool and app (and service), buried in the documentation or app codebases. So I'd like to propose we use something new, for example, `processor_` or `analyzer_`. I think they are more clearly indicating that what's wrapped is not any piece of software, but software that actually doing some data processing or analysis. 

And on the `app_` prefix, on second thought, now I think we might be better off without them. By not putting a prefix, 
1. I think we can signal a field is a first-class citizen as opposed to a secondary, optional field (`wrappee_version` or its successor). 
2. and in turn, developers are less likely to be confused between the idea of what's an `app` and what's a `tool`/`processor`/`analyzer`. 

And to that end, my proposal is 

* `app_version` -> `version`
* `wrappee_version` -> as discussion in the previous paragraph
* `mmif_version` stays `mmif_version` as there'd be little confusion between `app` and `mmif`, and also this field is automatically filled, so developers doesn't have to worry too much anyway.

**Comment by marcverhagen** [comment]
I do not share the worries about old usage of `tool`, but I can live with `analyzer`, which is pretty good.

On the prefix...

> I think we can signal a field is a first-class citizen as opposed to a secondary, optional field (wrappee_version or its successor).

Having a prefix determine whether something is optional does not sound like a good idea to me (one thing that spring to mind is that `mmif_version` would now be optional). And I think the current implementation which gives an error when you forget a non-optional property works fine.

> and in turn, developers are less likely to be confused between the idea of what's an app and what's a tool/processor/analyzer.

Not sure whether that makes any difference. But the most important part is to get our terms right, and there is more than one good answer there.

Finally, one big reason I do not like the use of `license` is that `license()` is a built-in function and the syntax highlighter will make it another color (mine does at least), it is like using `if` or `True` as a property.

**Comment by keighrim** [comment]
> Finally, one big reason I do not like the use of license is that license() is a built-in function and the syntax highlighter will make it another color (mine does at least), it is like using if or True as a property.

I think this is very valid point. And I agree on the point that what's important is us having terms completely ironed out. 

So to summarize; 

* `app_version` stays
* `license` -> `app_license`
* `wrappee_version` -> analyzer_version`
* `wrappee_license` -> `analyzer_license`
* everything else stays the same

**Comment by keighrim** [comment]
Closed via #86.
